language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

os:
  - osx
  - linux

matrix:
  include:
    - os: osx
      rust: stable
      env: TOOLCHAIN=IOS
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - |
    if [ -z "$TOOLCHAIN" ]
    then
      cargo test --verbose --all
    else
      if [ $TOOLCHAIN == "IOS" ]
      then
        rustup target add aarch64-apple-ios armv7-apple-ios armv7s-apple-ios x86_64-apple-ios i386-apple-ios
        cargo install cargo-lipo
        cargo lipo --release
      fi
    fi
