[workspace]
members = [
        "nekit_core",
        "nekit_connector",
        "nekit_http",
        "nekit_http_acceptor",
        "nekit_socks5_acceptor",
        "nekit_resolver",
        "nekit_io"
        ]