[workspace]
members = [
        "nekit-core",
        "nekit-connector",
        "nekit-http",
        "nekit-http-acceptor",
        "nekit-socks5-acceptor",
        "nekit-resolver",
        "nekit-io"
        ]