[package]
name = "nekit_connector"
version = "0.1.0"
authors = ["zhuhaow <zhuhaow@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "^0.1"
nekit_core = { path = "../nekit_core" }
nekit_resolver = { path = "../nekit_resolver" }

[lib]
crate-type = ["lib", "staticlib"]
