[package]
name = "specht2"
version = "0.1.0"
authors = ["zhuhaow <zhuhaow@gmail.com>"]
edition = "2018"

[dependencies]
freighter = { path = "../" }
tokio = "^0.1"

[lib]
crate-type = ["lib", "staticlib"]
