[package]
name = "nekit-resolver"
version = "0.1.0"
authors = ["zhuhaow <zhuhaow@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "^0.1"
trust-dns-resolver = "^0.10"
nekit-core = { path = "../nekit-core" }

[lib]
crate-type = ["lib", "staticlib"]